---
name: kigo
version: 17.08.1
summary: Go Board Game
description: Kigo is an open-source implementation of the popular Go game. Go is a
    strategic board game for two players. It is also known as igo (Japanese), weiqi
    or wei ch'i (Chinese) or baduk (Korean). Go is noted for being rich in strategic
    complexity despite its simple rules. The game is played by two players who alternately
    place black and white stones (playing pieces, now usually made of glass or plastic)
    on the vacant intersections of a grid of 19x19 lines (9x9 or 13x13 for easier
    games).
confinement: strict
grade: stable
apps:
    kigo:
        command: kf5-launch kigo
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kigo
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kigo:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - libkf5kdegames-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kigo-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
